name: CI

on: [issues, issue_comment]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: install dependencies
      run: |
        pip3 install setuptools --user
        pip3 install PyGithub --user
        pip3 install Flask --user
        pip3 install requests --user
        pip3 install pillow --user
    - name: run python script
      env:
        GITHUB_LOGIN: jwenjian
        GITHUB_PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: python3 main.py
    - uses: EndBug/add-and-commit@v9
      with:
        default_author: github_actions

